### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by sshivananda** [tidyjava/blogging-platform#1]
Can the readme file be updated with the dependencies/steps to get this running? That way, you can have more people who can contribute to your project

**Comment by tidyjava** [comment]
Sure, I'll do that later this week. I didn't expect anyone to contribute so early, but of course everybody is welcome :)

**Comment by tidyjava** [comment]
I updated the readme. You can have a look and let me know what you think. I will also update the issues tab soon.

**Comment by sshivananda** [comment]
@tidyjava Closing this!
