### ISSUE TITLE
Page width on pc is small

### ISSUE THREAD

**Issue by codingtim** [tidyjava/blogging-platform#33]
On pc the page width used is rather small. Perhaps the col-md to 6?

**Comment by tidyjava** [comment]
I don't like `col-md-6` too much, but I'll consult with someone who has better aesthetic sense than me :)

![image](https://cloud.githubusercontent.com/assets/18643108/19810935/a914e796-9d2f-11e6-9690-27e85e302306.png)

**Comment by tidyjava** [comment]
https://github.com/tidyjava/blogging-platform/pull/36
