### ISSUE TITLE
Gradle build fail in line 15 apply plugin: 'spring-boot'

### ISSUE THREAD

**Issue by YeWin** [tidyjava/blogging-platform#40]
When I start importing your project by using existing project from gradle, above error occurred like "could not install gradle distribution from eclipse". 

I added (io.spring.gradle:dependency-management-plugin:0.5.1.RELEASE") and error is okay but other Spring/Java error: namespace element 'annotation-config' … on JDK 1.5 and higher error occurred even my project is used jdk1.8.

I follow below link and try to build gradle but no used. 
-http://stackoverflow.com/questions/40963570/java-gradle-no-service-of-type-styled-text-output-factory-available-in-project-s
-http://stackoverflow.com/questions/23813369/spring-java-error-namespace-element-annotation-config-on-jdk-1-5-and-high

Could you please point out what I'm wrong with build.gradle file??

**Comment by tidyjava** [comment]
Hi,
I'll be completely honest with you: I suck at Gradle, so I won't be able to help.
Also, this project has been inactive for some time now and I don't plan to work on it anymore. Currently, it's there just to keep the links alive. I will update the readme to stress this fact.
Sorry for causing more trouble than good with the project!

**Comment by YeWin** [comment]
Hi tidy,

Thank you very much for your respond. So I decide to move Maven build because I also suck at Gradle. :)
I'm impressed the amount of code you produced. It's great references for me.

Thanks.
Ye.
